// Tom Hanks cluster
// Connections to: genres, studios, awards from file 01

// === People ===
g.addV('Person').property(id, 'person-tom-hanks').property('name', 'Tom Hanks').property('birthYear', 1956)
g.addV('Person').property(id, 'person-robert-zemeckis').property('name', 'Robert Zemeckis').property('birthYear', 1952)
g.addV('Person').property(id, 'person-robin-wright').property('name', 'Robin Wright').property('birthYear', 1966)
g.addV('Person').property(id, 'person-gary-sinise').property('name', 'Gary Sinise').property('birthYear', 1955)
g.addV('Person').property(id, 'person-steven-spielberg').property('name', 'Steven Spielberg').property('birthYear', 1946)
g.addV('Person').property(id, 'person-meg-ryan').property('name', 'Meg Ryan').property('birthYear', 1961)
g.addV('Person').property(id, 'person-michael-j-fox').property('name', 'Michael J. Fox').property('birthYear', 1961)
g.addV('Person').property(id, 'person-matt-damon').property('name', 'Matt Damon').property('birthYear', 1970)
g.addV('Person').property(id, 'person-tim-allen').property('name', 'Tim Allen').property('birthYear', 1953)
g.addV('Person').property(id, 'person-john-lasseter').property('name', 'John Lasseter').property('birthYear', 1957)
g.addV('Person').property(id, 'person-sam-mendes').property('name', 'Sam Mendes').property('birthYear', 1965)
g.addV('Person').property(id, 'person-paul-newman').property('name', 'Paul Newman').property('birthYear', 1925)
g.addV('Person').property(id, 'person-nora-ephron').property('name', 'Nora Ephron').property('birthYear', 1941)
g.addV('Person').property(id, 'person-wilson-the-volleyball').property('name', 'Wilson (Volleyball)').property('birthYear', 2000)

// === Movies ===
g.addV('Movie').property(id, 'movie-forrest-gump').property('title', 'Forrest Gump').property('year', 1994).property('rating', 8.8).property('tagline', 'Life is like a box of chocolates')
g.addV('Movie').property(id, 'movie-cast-away').property('title', 'Cast Away').property('year', 2000).property('rating', 7.8).property('tagline', 'At the edge of the world, his journey begins')
g.addV('Movie').property(id, 'movie-saving-private-ryan').property('title', 'Saving Private Ryan').property('year', 1998).property('rating', 8.6).property('tagline', 'The mission is a man')
g.addV('Movie').property(id, 'movie-philadelphia').property('title', 'Philadelphia').property('year', 1993).property('rating', 7.7).property('tagline', 'No one would take on his case... until one man was willing to take on the system')
g.addV('Movie').property(id, 'movie-big').property('title', 'Big').property('year', 1988).property('rating', 7.3).property('tagline', 'Have you ever had a really big secret?')
g.addV('Movie').property(id, 'movie-sleepless-in-seattle').property('title', 'Sleepless in Seattle').property('year', 1993).property('rating', 6.8).property('tagline', 'What if someone you never met, someone you never saw, someone you never knew was the only someone for you?')
g.addV('Movie').property(id, 'movie-youve-got-mail').property('title', "You've Got Mail").property('year', 1998).property('rating', 6.6).property('tagline', 'Someone you pass on the street may already be the love of your life')
g.addV('Movie').property(id, 'movie-toy-story').property('title', 'Toy Story').property('year', 1995).property('rating', 8.3).property('tagline', 'The adventure takes off!')
g.addV('Movie').property(id, 'movie-back-to-the-future').property('title', 'Back to the Future').property('year', 1985).property('rating', 8.5).property('tagline', "He's the only kid ever to get into trouble before he was born")
g.addV('Movie').property(id, 'movie-road-to-perdition').property('title', 'Road to Perdition').property('year', 2002).property('rating', 7.7).property('tagline', 'Pray for Michael Sullivan')
g.addV('Movie').property(id, 'movie-the-green-mile').property('title', 'The Green Mile').property('year', 1999).property('rating', 8.6).property('tagline', 'Miracles do happen')

// === ACTED_IN ===
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-forrest-gump')).property('role', 'Forrest Gump')
g.V('person-robin-wright').addE('ACTED_IN').to(g.V('movie-forrest-gump')).property('role', 'Jenny Curran')
g.V('person-gary-sinise').addE('ACTED_IN').to(g.V('movie-forrest-gump')).property('role', 'Lt. Dan Taylor')
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-cast-away')).property('role', 'Chuck Noland')
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-saving-private-ryan')).property('role', 'Captain John H. Miller')
g.V('person-matt-damon').addE('ACTED_IN').to(g.V('movie-saving-private-ryan')).property('role', 'Private James Francis Ryan')
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-philadelphia')).property('role', 'Andrew Beckett')
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-big')).property('role', 'Josh Baskin')
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-sleepless-in-seattle')).property('role', 'Sam Baldwin')
g.V('person-meg-ryan').addE('ACTED_IN').to(g.V('movie-sleepless-in-seattle')).property('role', 'Annie Reed')
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-youve-got-mail')).property('role', 'Joe Fox')
g.V('person-meg-ryan').addE('ACTED_IN').to(g.V('movie-youve-got-mail')).property('role', 'Kathleen Kelly')
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-toy-story')).property('role', 'Woody')
g.V('person-tim-allen').addE('ACTED_IN').to(g.V('movie-toy-story')).property('role', 'Buzz Lightyear')
g.V('person-michael-j-fox').addE('ACTED_IN').to(g.V('movie-back-to-the-future')).property('role', 'Marty McFly')
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-road-to-perdition')).property('role', 'Michael Sullivan')
g.V('person-paul-newman').addE('ACTED_IN').to(g.V('movie-road-to-perdition')).property('role', 'John Rooney')
g.V('person-tom-hanks').addE('ACTED_IN').to(g.V('movie-the-green-mile')).property('role', 'Paul Edgecomb')

// === DIRECTED ===
g.V('person-robert-zemeckis').addE('DIRECTED').to(g.V('movie-forrest-gump'))
g.V('person-robert-zemeckis').addE('DIRECTED').to(g.V('movie-cast-away'))
g.V('person-robert-zemeckis').addE('DIRECTED').to(g.V('movie-back-to-the-future'))
g.V('person-steven-spielberg').addE('DIRECTED').to(g.V('movie-saving-private-ryan'))
g.V('person-john-lasseter').addE('DIRECTED').to(g.V('movie-toy-story'))
g.V('person-nora-ephron').addE('DIRECTED').to(g.V('movie-sleepless-in-seattle'))
g.V('person-nora-ephron').addE('DIRECTED').to(g.V('movie-youve-got-mail'))
g.V('person-sam-mendes').addE('DIRECTED').to(g.V('movie-road-to-perdition'))

// === HAS_GENRE ===
g.V('movie-forrest-gump').addE('HAS_GENRE').to(g.V('genre-drama'))
g.V('movie-forrest-gump').addE('HAS_GENRE').to(g.V('genre-romance'))
g.V('movie-cast-away').addE('HAS_GENRE').to(g.V('genre-drama'))
g.V('movie-cast-away').addE('HAS_GENRE').to(g.V('genre-adventure'))
g.V('movie-saving-private-ryan').addE('HAS_GENRE').to(g.V('genre-drama'))
g.V('movie-saving-private-ryan').addE('HAS_GENRE').to(g.V('genre-war'))
g.V('movie-philadelphia').addE('HAS_GENRE').to(g.V('genre-drama'))
g.V('movie-big').addE('HAS_GENRE').to(g.V('genre-comedy'))
g.V('movie-big').addE('HAS_GENRE').to(g.V('genre-fantasy'))
g.V('movie-sleepless-in-seattle').addE('HAS_GENRE').to(g.V('genre-romance'))
g.V('movie-sleepless-in-seattle').addE('HAS_GENRE').to(g.V('genre-comedy'))
g.V('movie-youve-got-mail').addE('HAS_GENRE').to(g.V('genre-romance'))
g.V('movie-youve-got-mail').addE('HAS_GENRE').to(g.V('genre-comedy'))
g.V('movie-toy-story').addE('HAS_GENRE').to(g.V('genre-animation'))
g.V('movie-toy-story').addE('HAS_GENRE').to(g.V('genre-comedy'))
g.V('movie-back-to-the-future').addE('HAS_GENRE').to(g.V('genre-scifi'))
g.V('movie-back-to-the-future').addE('HAS_GENRE').to(g.V('genre-adventure'))
g.V('movie-road-to-perdition').addE('HAS_GENRE').to(g.V('genre-crime'))
g.V('movie-road-to-perdition').addE('HAS_GENRE').to(g.V('genre-drama'))
g.V('movie-the-green-mile').addE('HAS_GENRE').to(g.V('genre-drama'))
g.V('movie-the-green-mile').addE('HAS_GENRE').to(g.V('genre-fantasy'))

// === PRODUCED_BY ===
g.V('movie-forrest-gump').addE('PRODUCED_BY').to(g.V('studio-paramount'))
g.V('movie-cast-away').addE('PRODUCED_BY').to(g.V('studio-fox'))
g.V('movie-cast-away').addE('PRODUCED_BY').to(g.V('studio-dreamworks'))
g.V('movie-saving-private-ryan').addE('PRODUCED_BY').to(g.V('studio-dreamworks'))
g.V('movie-saving-private-ryan').addE('PRODUCED_BY').to(g.V('studio-paramount'))
g.V('movie-philadelphia').addE('PRODUCED_BY').to(g.V('studio-columbia'))
g.V('movie-big').addE('PRODUCED_BY').to(g.V('studio-fox'))
g.V('movie-sleepless-in-seattle').addE('PRODUCED_BY').to(g.V('studio-columbia'))
g.V('movie-youve-got-mail').addE('PRODUCED_BY').to(g.V('studio-warner'))
g.V('movie-toy-story').addE('PRODUCED_BY').to(g.V('studio-disney'))
g.V('movie-back-to-the-future').addE('PRODUCED_BY').to(g.V('studio-universal'))
g.V('movie-road-to-perdition').addE('PRODUCED_BY').to(g.V('studio-dreamworks'))
g.V('movie-the-green-mile').addE('PRODUCED_BY').to(g.V('studio-warner'))

// === WON_AWARD ===
g.V('person-tom-hanks').addE('WON_AWARD').to(g.V('award-best-actor')).property('year', 1994)
g.V('person-tom-hanks').addE('WON_AWARD').to(g.V('award-best-actor')).property('year', 1995)
g.V('movie-forrest-gump').addE('WON_AWARD').to(g.V('award-best-picture')).property('year', 1995)
g.V('person-robert-zemeckis').addE('WON_AWARD').to(g.V('award-best-director')).property('year', 1995)
g.V('person-steven-spielberg').addE('WON_AWARD').to(g.V('award-best-director')).property('year', 1994)
