services:
  database:
    image: tinkerpop/gremlin-server:3.8
    ports:
      - "8282:8182"
    volumes:
      - ./sample:/opt/gremlin-server/sample:ro
    entrypoint: /opt/gremlin-server/bin/gremlin-server.sh
    command: /opt/gremlin-server/sample/conf/gremlin-server-air-routes.yaml
