services:
  app:
    build:
      context: ../../
      dockerfile: samples/dev_air_routes/Dockerfile
    ports:
      - "5173:5173"
      - "8080:80"
    environment:
      - HOST=localhost
      - PUBLIC_OR_PROXY_ENDPOINT=http://localhost:8080
      - GRAPH_TYPE=gremlin
      - USING_PROXY_SERVER=true
      - PROXY_SERVER_HTTPS_CONNECTION=false
      - GRAPH_CONNECTION_URL=http://database:8182
    volumes:
      - ../../packages/graph-explorer/src:/graph-explorer/packages/graph-explorer/src
      - ../../packages/graph-explorer-proxy-server/src:/graph-explorer/packages/graph-explorer-proxy-server/src
      - ../../packages/shared/src:/graph-explorer/packages/shared/src

  database:
    image: tinkerpop/gremlin-server:latest
    volumes:
      - ../air_routes/sample:/opt/gremlin-server/sample
    command: /opt/gremlin-server/sample/conf/gremlin-server-air-routes.yaml
