import type { LocalDataPayload } from "./types";

/** A small air routes sample dataset for trying out Local Data connections. */
export const sampleDataPayload: LocalDataPayload = {
  meta: {
    version: "1",
    name: "Air Routes Sample",
    description: "A small subset of airports and routes for exploration",
    source: "graph-explorer-sample",
  },
  data: {
    graph: {
      vertices: [
        {
          id: "ATL",
          type: "Airport",
          attributes: {
            code: "ATL",
            city: "Atlanta",
            country: "US",
            runways: 5,
            longest: 12390,
          },
        },
        {
          id: "ORD",
          type: "Airport",
          attributes: {
            code: "ORD",
            city: "Chicago",
            country: "US",
            runways: 7,
            longest: 13000,
          },
        },
        {
          id: "DFW",
          type: "Airport",
          attributes: {
            code: "DFW",
            city: "Dallas",
            country: "US",
            runways: 7,
            longest: 13401,
          },
        },
        {
          id: "DEN",
          type: "Airport",
          attributes: {
            code: "DEN",
            city: "Denver",
            country: "US",
            runways: 6,
            longest: 16000,
          },
        },
        {
          id: "LAX",
          type: "Airport",
          attributes: {
            code: "LAX",
            city: "Los Angeles",
            country: "US",
            runways: 4,
            longest: 12091,
          },
        },
        {
          id: "JFK",
          type: "Airport",
          attributes: {
            code: "JFK",
            city: "New York",
            country: "US",
            runways: 4,
            longest: 14511,
          },
        },
        {
          id: "SFO",
          type: "Airport",
          attributes: {
            code: "SFO",
            city: "San Francisco",
            country: "US",
            runways: 4,
            longest: 11870,
          },
        },
        {
          id: "SEA",
          type: "Airport",
          attributes: {
            code: "SEA",
            city: "Seattle",
            country: "US",
            runways: 3,
            longest: 11901,
          },
        },
        {
          id: "LHR",
          type: "Airport",
          attributes: {
            code: "LHR",
            city: "London",
            country: "GB",
            runways: 2,
            longest: 12799,
          },
        },
        {
          id: "NRT",
          type: "Airport",
          attributes: {
            code: "NRT",
            city: "Tokyo",
            country: "JP",
            runways: 2,
            longest: 13123,
          },
        },
        {
          id: "US",
          type: "Country",
          attributes: { name: "United States", continent: "North America" },
        },
        {
          id: "GB",
          type: "Country",
          attributes: { name: "United Kingdom", continent: "Europe" },
        },
        {
          id: "JP",
          type: "Country",
          attributes: { name: "Japan", continent: "Asia" },
        },
      ],
      edges: [
        // Routes
        {
          id: "r1",
          type: "route",
          source: "ATL",
          target: "ORD",
          attributes: { distance: 606 },
        },
        {
          id: "r2",
          type: "route",
          source: "ATL",
          target: "DFW",
          attributes: { distance: 731 },
        },
        {
          id: "r3",
          type: "route",
          source: "ATL",
          target: "LAX",
          attributes: { distance: 1946 },
        },
        {
          id: "r4",
          type: "route",
          source: "ATL",
          target: "JFK",
          attributes: { distance: 760 },
        },
        {
          id: "r5",
          type: "route",
          source: "ORD",
          target: "DEN",
          attributes: { distance: 888 },
        },
        {
          id: "r6",
          type: "route",
          source: "ORD",
          target: "LAX",
          attributes: { distance: 1745 },
        },
        {
          id: "r7",
          type: "route",
          source: "ORD",
          target: "SFO",
          attributes: { distance: 1846 },
        },
        {
          id: "r8",
          type: "route",
          source: "DFW",
          target: "DEN",
          attributes: { distance: 641 },
        },
        {
          id: "r9",
          type: "route",
          source: "DFW",
          target: "LAX",
          attributes: { distance: 1235 },
        },
        {
          id: "r10",
          type: "route",
          source: "DEN",
          target: "SFO",
          attributes: { distance: 967 },
        },
        {
          id: "r11",
          type: "route",
          source: "DEN",
          target: "SEA",
          attributes: { distance: 1024 },
        },
        {
          id: "r12",
          type: "route",
          source: "LAX",
          target: "SFO",
          attributes: { distance: 337 },
        },
        {
          id: "r13",
          type: "route",
          source: "LAX",
          target: "NRT",
          attributes: { distance: 5451 },
        },
        {
          id: "r14",
          type: "route",
          source: "JFK",
          target: "LHR",
          attributes: { distance: 3451 },
        },
        {
          id: "r15",
          type: "route",
          source: "JFK",
          target: "SFO",
          attributes: { distance: 2586 },
        },
        {
          id: "r16",
          type: "route",
          source: "SFO",
          target: "NRT",
          attributes: { distance: 5130 },
        },
        {
          id: "r17",
          type: "route",
          source: "SFO",
          target: "SEA",
          attributes: { distance: 679 },
        },
        {
          id: "r18",
          type: "route",
          source: "LHR",
          target: "NRT",
          attributes: { distance: 5974 },
        },
        // Country relationships
        {
          id: "c1",
          type: "locatedIn",
          source: "ATL",
          target: "US",
        },
        {
          id: "c2",
          type: "locatedIn",
          source: "ORD",
          target: "US",
        },
        {
          id: "c3",
          type: "locatedIn",
          source: "DFW",
          target: "US",
        },
        {
          id: "c4",
          type: "locatedIn",
          source: "DEN",
          target: "US",
        },
        {
          id: "c5",
          type: "locatedIn",
          source: "LAX",
          target: "US",
        },
        {
          id: "c6",
          type: "locatedIn",
          source: "JFK",
          target: "US",
        },
        {
          id: "c7",
          type: "locatedIn",
          source: "SFO",
          target: "US",
        },
        {
          id: "c8",
          type: "locatedIn",
          source: "SEA",
          target: "US",
        },
        {
          id: "c9",
          type: "locatedIn",
          source: "LHR",
          target: "GB",
        },
        {
          id: "c10",
          type: "locatedIn",
          source: "NRT",
          target: "JP",
        },
      ],
    },
  },
};
